# See https://ishansoninitj.medium.com/introduction-to-spring-cloud-function-and-spring-cloud-stream-19ff3477f6bc
version: “3.8”
services:
  # http://localhost:15672
  # username: guest password: guest
  rabbitmq:
    image: rabbitmq:3.11-management-alpine
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      RABBITMQ_DEFAULT_VHOST: /