version: '3.8'

services:
  
  #  http://localhost:15672
  # UserId/Password : guest/guest
  rabbitmq:
    image: rabbitmq:3
    hostname: my-rabbit
    ports:
      - "5672:5672"
    container_name: some-rabbit
    restart: unless-stopped
